export const GET_ERRORS = 'GET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const GET_PROFILE = 'GET_PROFILE'
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'

export const FIXEDASSETS_LOADING = 'FIXEDASSETS_LOADING'
export const GET_FIXEDASSETS = 'GET_FIXEDASSETS'
export const GET_FIXEDASSET = 'GET_FIXEDASSET'
export const ADD_FIXEDASSET = 'ADD_FIXEDASSET'
export const DELETE_FIXEDASSET = 'DELETE_FIXEDASSET'

export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING'
export const GET_DEPARTMENTS = 'GET_DEPARTMENTS'  ``
export const GET_DEPARTMENT = 'GET_DEPARTMENT'
export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS'
export const DELETE_DEPARTMENTS = 'DELETE_DEPARTMENTS'

export const LOCATIONS_LOADING = 'LOCATIONS_LOADING'
export const GET_LOCATIONS = 'GET_LOCATIONS'  ``
export const GET_LOCATION = 'GET_LOCATION'
export const ADD_LOCATIONS = 'ADD_LOCATIONS'
export const DELETE_LOCATIONS = 'DELETE_LOCATIONS'

export const COUNTRYS_LOADING = 'COUNTRYS_LOADING'
export const GET_COUNTRYS = 'GET_COUNTRYS'  ``
export const GET_COUNTRY = 'GET_COUNTRY'
export const ADD_COUNTRYS = 'ADD_COUNTRYS'
export const DELETE_COUNTRYS = 'DELETE_COUNTRYS'

export const INSURERS_LOADING = 'INSURERS_LOADING'
export const GET_INSURERS = 'GET_INSURERS'  ``
export const GET_INSURER = 'GET_INSURER'
export const ADD_INSURERS = 'ADD_INSURERS'
export const DELETE_INSURERS = 'DELETE_INSURERS'

export const POST_LOADING = 'POST_LOADING'
export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'
export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'
