export const GET_ERRORS = 'GET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'
export const PROFILE_LOADING = 'PROFILE_LOADING'
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND'
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE'


export const GET_FIXEDASSETS = 'GET_FIXEDASSETS'
export const FIXEDASSETS_LOADING = 'FIXEDASSETS_LOADING'
export const FIXEDASSETS_NOT_FOUND = 'FIXEDASSETS_NOT_FOUND'
export const CLEAR_CURRENT_FIXEDASSETS = 'CLEAR_CURRENT_FIXEDASSETS'